apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-internal-loadbalancer-deployment
  labels:
    app: admission-internal-loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-internal-loadbalancer
  template:
    metadata:
      labels:
        app: admission-internal-loadbalancer
    spec:
      containers:
        - name: admission-internal-loadbalancer
          image: docktofuture/admission-internal-loadbalancer:v1
          imagePullPolicy: Always
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: admission-internal-loadbalancer-certs
