apiVersion: v1
kind: Service
metadata:
  name: admission-internal-loadbalancer-svc
  labels:
    app: admission-internal-loadbalancer
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: admission-internal-loadbalancer
